# -*- coding: utf-8 -*-
"""Estatistica_Python_TurmaA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rAsi20NUkBKxgygChENUhqVuaxPSOyzs

# **Introdução ao Python**

Vamos conhecer os seguintes conceitos iniciais:

*   Variaveis
*   Imprimir na tela
* Operações Matemática
* Arredondamento
* Função input
* Listas
* Diciopnários
* Dataframes
* Bibliotecas

## **Variáveis, print e arredondamento**
"""

disciplina          = "Estatística"   # String (palavra/frase)
quantidade_alunos   = 49              # Int (número interiro)
quantiade_aprovados = 37              # Int (número interiro)
media_geral         = 7.5             # Float (número real)

#taxa_aprovacao      = round((quantiade_aprovados/quantidade_alunos)*100,1)

taxa_aprovacao_decimal      = quantiade_aprovados/quantidade_alunos
taxa_aprovacao_percentual   = round(taxa_aprovacao_decimal*100, 1)

print(taxa_aprovacao_decimal)
print(taxa_aprovacao_percentual, "%")

print(f"A taxa de aprovação da disciplina {disciplina} é: {taxa_aprovacao}%")

"""## **Interagindo com Pytyhon: input e Listas**"""

nome = input("Qual seu nome?")

n1 = float(input("Digite sua nota 1:"))
n2 = float(input("Digite sua nota 2:"))
n3 = float(input("Digite sua nota 3:"))

lista_notas = [n1, n2, n3]

soma = sum(lista_notas) #A função 'sum' soma o valor dos objetos que estão dentro da lista
qtade_notas = len(lista_notas)  #A função 'len' conta quantos objetos que estão dentro da lista

media = soma/qtade_notas

print(soma)
print(qtade_notas)
print(f"A média das notas é {media:.2f}")

import numpy as np

media_lista = np.mean(lista_notas)
print(f"A média das notas é {media_lista:.2f}")

"""
PROBLEMA: Calcular a n3 para aprovação, dados
a nota 1, nota2 e média mínima para aprovação

"""

# COLETAR INFORMAÇÕES INICIAIS
media_apr = float(input("Qual é a média para aprovação?")) # média mínima
nota1 = float(input("Qual foi a nota na prova 1?"))        # nota 1
nota2 = float(input("Qual foi a nota na prova 2?"))        # nota 2

# PROCESSAMENTO DOS DADOS
nota3 = media_apr * 3 - nota1 - nota2

# IMPRIMIR O RESULTADO
print("A nota necessária na avaliação 3 é:", round(nota3, 2))
print(f"A nota necessária na avaliação 3 é: {nota3:.1f}")

"""**PROBLEMA 2**: Informar o preço de custo para um usuário conhecendo o preço de venda e a margem de lucro."""

# 1º PASSO: ENTRADA DOS DADOS

preco_venda = 2.59
margem_lucro = 35 #em valor percentual

# 2º PASSO: PROCESSMAENTO DOS DADOS

preco_custo = preco_venda / (1 + margem_lucro/100)

# 3º PASSO: IMPRIME OS RESULTADOS

print(f"O preço de custo é: R${round(preco_custo, 2)}")

"""## **Dicionários e DataFrame**"""

# Armazenar vários conjuntos de dados em um único objeto, o dicionário
dicionario = {
    'Nome': ["Aluno 1", "Aluno 2", "Aluno 3"],
    'Nota 1': [4.5, 9.8, 7.1],
    'Nota 2': [5.0, 8.2, 3.8],
    'Nota 3': [6.5, 8.3, 9.1]}

print(dicionario)

# Importar uma biblioteca para trabalhar com DataFrames
import pandas as pd

# Converter o dicionário em um DataFrame

df = pd.DataFrame(dicionario)

df.head()
#print(df)

# Inserir uma nova coluna no df com o valor das médias

df["Médias"] = (df["Nota 1"] + df["Nota 2"] + df["Nota 3"]) / 3
df["Médias"] = round(df["Médias"], 1)

df.head()

import numpy as np

media_n3 = np.mean(df['Nota 3'])

print(f"A médias das Notas 3 é: {media_n3}")
#print(f"A tabela é: \n\n {df}")

"""## **Importandos dados externos**"""

import pandas as pd

df_bcd = pd.read_excel("Dados_CalourosBCD.xlsx")

df_bcd.describe()
#df_bcd.info()
#df_bcd.head(30)

media_cidades = np.mean(df_bcd['Você já morou em quantas cidades diferentes?'])
std_cidades = np.std(df_bcd['Você já morou em quantas cidades diferentes?'])

print(media_cidades)
print(std_cidades)

"""# **Medidas de Posição**"""

# Importar as bibliotecas
import pandas as pd
import numpy as np

df = pd.read_excel("[Estatistica-BCD]_DadosTratados_CalourosBCD_turmA.xlsx",
                   sheet_name="DadosTratados2")

df.info()

# Seleção da variável analisada
idade = df['Idade']
trabalho = df['Modo_Trab']

# Média Artirmética Simples
media_aritmetica1 = idade.mean()
media_aritmetica2 = np.mean(idade)

# Média Ponderada
notas = [6.5, 7.0, 8.1]
pesos = [0.1, 0.4, 0.5]
media_ponderada = np.average(notas, weights=pesos)

# Média Aparada
from scipy.stats import trim_mean
media_aparada = trim_mean(idade, 0.2)

# Mediana
mediana1 = np.median(idade)
mediana2 = np.nanmedian(idade)

# Moda
import statistics
valores = [1, 1, 2, 3, 4, 4, 5]

moda1 = statistics.mode(trabalho)
moda2 = trabalho.mode()
moda_multi = statistics.multimode(valores)


# Imprimir Resultados
print(f'Média ponderada = {media_ponderada:.2f}')
print(f'Média aritmética = {media_aritmetica2:.2f}')
print(f'Média aparada = {media_aparada:.2f}')
print(f'Mediana = {mediana2:.2f}')
print(f'Moda = {moda1}')
print(f'Moda Multimodal = {moda_multi}')

"""# **Medidas de Dispersão**"""

# Importar bibliotecas
import pandas as pd
import numpy as np

# Carregar os dados

df = pd.read_excel("[Estatistica-BCD]_DadosTratados_CalourosBCD_turmA.xlsx",
                   sheet_name="DadosTratados2")

df.info()

# Selecionar variáveis
idades_outras = df[df['Cidade_Origem'] != 'Blumenau']['Idade'].tolist()

idades_bnu = df[df['Cidade_Origem'] == 'Blumenau']['Idade'].tolist()

print(idades_outras)
print(idades_bnu)

########################################
#### Calculo de medidas de posição #####
########################################

# Amplitude total
amp_outras = np.max(idades_outras)-np.min(idades_outras)
amp_bnu = np.nanmax(idades_bnu)-np.nanmin(idades_bnu)

# Desvio médio
mae_outras = np.mean(np.abs(idades_outras - np.mean(idades_outras)))
mae_bnu = np.nanmean(np.abs(idades_bnu - np.nanmean(idades_bnu)))

# Variância
var_outras = np.var(idades_outras, ddof=1)
var_bnu = np.nanvar(idades_bnu, ddof=1)

# Desvio padrão
std_outras = np.std(idades_outras, ddof=1)
std_bnu = np.nanstd(idades_bnu, ddof=1)

# Coeficiente de variação
cv_outras = (std_outras/np.mean(idades_outras))*100
cv_bnu = (std_bnu/np.nanmean(idades_bnu))*100


# Imprimir resultados
print(f'Média (outras cidades) = {np.mean(idades_outras):.2f}')
print(f'Média (Blumenau) = {np.nanmean(idades_bnu):.2f}\n')
print(f'Amplitude (outras cidades) = {amp_outras}')
print(f'Amplitude (Blumenau) = {amp_bnu}\n')
print(f'Desvio médio (outras cidades) = {mae_outras:.2f}')
print(f'Desvio médio (Blumenau) = {mae_bnu:.2f}\n')
print(f'Variância (outras cidades) = {var_outras:.2f}')
print(f'Variância (Blumenau) = {var_bnu:.2f}\n')
print(f'DesvPad (outras cidades) = {std_outras:.2f}')
print(f'DesvPad (Blumenau) = {std_bnu:.2f}\n')
print(f'CV (outras cidades) = {cv_outras:.1f}')
print(f'CV (Blumenau) = {cv_bnu:.1f}')

"""# **Definição de Funções**

Automatizar a cálculo de estatísticas descritivas de conjunto de dados
"""

# Importar bibliotecas
import pandas as pd
import numpy as np
import statistics

# Carregar a base de dados

df = pd.read_excel("[Estatistica-BCD]_DadosTratados_CalourosBCD_turmA.xlsx",
                   sheet_name="DadosTratados2")

df.info()

# Definir funções para Estatística Descrita

def descritiva_quanti(dataset, variavel):
  """
  Parâmetros de entrada:
  dataset: um dataframe
  variável: nome de um variável "string"
  """
  # 1.Filtrar a variável analisada
  coluna = dataset[variavel]

  # 2.Calcular medidas de posição
  media   = round(np.nanmean(coluna), 1)
  mediana = round(np.nanmedian(coluna), 1)

  # 3.Calcular medidas de dispersão
  min = round(np.min(coluna), 1)
  max = round(np.max(coluna), 1)
  amp = max - min
  var = round(np.nanvar(coluna, ddof=1), 1)
  std = round(np.nanstd(coluna, ddof=1), 1)
  cv  = round((std/media) * 100, 1)

  # 4.Agrupar os resultados em um dicionário
  resultados = {
      'Variavel': variavel,
      'Media': media,
      'Mediana': mediana,
      'Mínimo': min,
      'Max': max,
      'Amplitude': amp,
      'Variância': var,
      'Desvio Padrão': std,
      'CV (%)': cv}

  # 5.Converter o dicionário em um DataFrame
  df_final = pd.DataFrame([resultados])

  # 6.Definir qual será a saída da função
  return df_final


def descritiva_quanli(dataset, variavel):
  """
  Parâmetros de entrada:
  dataset: um dataframe
  variável: nome de um variável "string"
  """
  # 1.Filtrar a variável analisada
  coluna = dataset[variavel]

  # 2.Calcular medidas de posição
  moda = statistics.multimode(coluna)

  # 3.Calcular medidas de dispersão
  ### Razão de Variação
  n   = len(coluna.dropna())
  f_m = coluna.value_counts().max() #frequência da moda
  rv  = round(1 - (f_m/n), 1)

  # 4.Agrupar os resultados em um dicionário
  resultados = {
      'Variavel': variavel,
      'Moda': moda,
      'RV': rv}

  # 5.Converter o dicionário em um DataFrame
  df_final = pd.DataFrame([resultados])

  # 6.Definir qual será a saída da função
  return df_final

# Calcular resumos estatísticos de dados quantitativos

resumo_quanti = descritiva_quanti(df ,"Leituras")
resumo_quanti

# Calcular resumos estatísticos de dados qualitativos

resumo_quanli = descritiva_quanli(df ,"Cidade_Origem")
resumo_quanli

"""# **Gráficos**

Biblioteca MatPlotLib: https://matplotlib.org/stable/index.html
"""

import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

# Carregar os dados
df = pd.read_excel("[Estatistica-BCD]_DadosTratados_CalourosBCD_turmA.xlsx",
                   sheet_name='DadosTratados2')

"""### _Gráfico de Barras_"""

# 1. Preparação dos dados
cidades = ['Blumenau', 'Gaspar', 'Indaial', 'Timbó']
frequencias = [23, 18, 12, 10]

# 2. Criação da figura
plt.figure(figsize=(6, 3))

# 3. Plotagem do gráfico de barras
plt.bar(cidades, frequencias, color='violet')

# 4. Elementos de identificação
plt.title('Distribuição dos alunos por cidade de origem',
          fontsize=14,
          fontweight='bold',
          pad=10)
plt.xlabel('Cidades', fontsize=10)
plt.ylabel('Frequência absoluta', fontsize=10)

# 5. Definir a escala do eixo Y
plt.ylim(0, max(frequencias) + 5)

# 6. Adicionando linhas de grade
plt.grid(axis='y', linestyle='--', alpha=0.5)

# 7. Exibição do gráfico
plt.tight_layout()

# Salvando a imagem
#plt.savefig("Gráfico de Barras.png", dpi=300)

plt.show()

# 1. Dados
contagem = df['Cidade_Reside'].value_counts()
valores = contagem.values
legendas = contagem.index

# 2. Criar o gráfico de barras
plt.figure(figsize=(6, 3))
plt.bar(legendas, valores, color='navy', edgecolor='black')

# 3. Personalização
plt.title("Cidade de origem dos alunos", fontsize=15, fontweight='bold')
plt.xlabel("Cidades", fontsize=10, fontweight='bold')
plt.ylabel("Frequência absoluta", fontsize=10, fontweight='bold')
plt.xticks(rotation=30)
plt.grid(axis='y', linestyle='--', alpha=0.5)
plt.ylim(0, max(valores) + 2)

# 4. Exibição do gráfico
plt.tight_layout()
plt.show()

"""### _Gráfico de Setores_"""

# 1. Dados
cidades = ['Blumenau', 'Gaspar', 'Indaial', 'Timbó']
frequencias = [23, 12, 8, 5]
cores = ['#ff9999','#66b3ff','#99ff99','#ffcc99']

# 2. Configuração da figura
plt.figure(figsize=(5, 5))

# 3. Criando o gráfico de pizza
plt.pie(frequencias,
        labels=cidades,        # Nomes das cidades nas fatias
        autopct='%1.1f%%',     # Formata e exibe a porcentagem automaticamente
        startangle=90,         # Rotaciona o gráfico para começar no topo (12h)
        colors=cores,          # Aplica a paleta de cores
        pctdistance=0.85)      # Distância da porcentagem em relação ao centro

# 4. Título
plt.title('Proporção de alunos por cidade de origem', fontsize=14,
          fontweight='bold', pad=10)

# 5. Exibição
plt.tight_layout()
plt.show()

# 1. Dados
contagem = df['Programacao'].value_counts()
valores = contagem.values
legendas = contagem.index

# 2. Definindo as cores
# O número de cores deve ser igual ao número de fatias (len(contagem))
"""
Escolha de paletas de cores:
https://matplotlib.org/stable/users/explain/colors/colormaps.html
"""
cores = plt.get_cmap('Pastel2')(range(len(contagem)))

# 3. Configuração da figura
plt.figure(figsize=(5, 5))

# 4. Criando o gráfico de pizza
plt.pie(valores,
        labels=legendas,       # Nomes das cidades nas fatias
        autopct='%1.1f%%',     # Formata e exibe a porcentagem automaticamente
        startangle=90,         # Rotaciona o gráfico para começar no topo (12h)
        colors=cores,          # Aplica a paleta de cores
        pctdistance=0.85)      # Distância da porcentagem em relação ao centro

# 5. Título
plt.title('Experiência com programação da turma', fontsize=14,
          fontweight='bold', pad=20)

# 6. Exibição
plt.tight_layout()
plt.show()

"""### _Histograma_"""

# 1. Gerando dados fictícios/aleatórios
np.random.seed(42) # Garante que irá gerar sempre a mesma sequência de dados
idades = np.random.normal(25, 5, 100).astype(int) # Média 25, Desvio 5

# 2. Criando o Histograma
""" bin = 1 + 3,3*log(N) """
plt.figure(figsize=(5, 5))
plt.hist(idades, bins=8, color='seagreen', edgecolor='black', alpha=0.7)

# 3. Elementos do gráfico
plt.title('Distribuição de idades', fontsize=14, fontweight='bold')
plt.xlabel('Idade (Anos)', fontsize=12)
plt.ylabel('Frequência absoluta', fontsize=12)

# 4. Ajustes
plt.grid(axis='y', alpha=0.3)
plt.tight_layout()
plt.show()

# 1. Dados do questionário
idades = df['Idade']

# 2. Criando o Histograma
plt.figure(figsize=(5, 5))
plt.hist(idades, bins=7, color='seagreen', edgecolor='black', alpha=0.7)

# 3. Elementos do gráfico
plt.title('Distribuição de idades \ndos calouros em BCD', fontsize=14, fontweight='bold')
plt.xlabel('Idade (Anos)', fontsize=12)
plt.ylabel('Frequência absoluta', fontsize=12)

# 4. Ajustes
plt.grid(axis='y', alpha=0.3)
plt.tight_layout()
plt.show()

"""### _Gráfico de Linha_"""

# 1. Dados
avaliacoes = ['Prova 1', 'Prova 2', 'Prova 3', 'Prova 4']
notas_medias = [6.5, 7.2, 6.8, 8.5]

# 2. Criando o gráfico de linhas
plt.figure(figsize=(7, 5))
plt.plot(avaliacoes, notas_medias, marker='o', linestyle='-',
         color='red', linewidth=2)

# 3. Elementos do gráfico
plt.title('Evolução do desempenho médio da turma',
          fontsize=14, fontweight='bold')
plt.xlabel('Avaliações ao longo do semestre', fontsize=12)
plt.ylabel('Nota Média', fontsize=12)
plt.ylim(0, 10)

# 4. Estética
plt.grid(True, linestyle='--', alpha=0.6)
plt.tight_layout()
plt.show()

"""### _Gráfico de Dispersão_"""

# 1. Dados: Horas de Estudo vs. Nota na Prova
horas_estudo = [2, 5, 1, 8, 10, 4, 7, 3, 6, 9]
notas = [5.0, 7.5, 4.0, 8.5, 9.5, 6.0, 8.0, 5.5, 7.0, 9.0]

# 2. Criando o gráfico de dispersão
plt.figure(figsize=(6, 5))
plt.scatter(horas_estudo, notas, color='purple',
            s=80, alpha=0.7, edgecolors='black')

# 3. Elementos do gráfico
plt.title('Horas de Estudo x Desempenho Acadêmico',
          fontsize=14, fontweight='bold')
plt.xlabel('Horas de Estudo (por semana)', fontsize=12)
plt.ylabel('Nota Final', fontsize=12)

# 4. Ajustes de escala
plt.xlim(0, 12)
plt.ylim(0, 10)

# 5. Estética
plt.grid(True, linestyle=':', alpha=0.6)
plt.tight_layout()
plt.show()

# 1. Dados: Horas de Estudo vs. Nota na Prova
var1 = df['Idade']
var2 = df['Leituras']

# 2. Criando o gráfico de dispersão
plt.figure(figsize=(6, 5))
plt.scatter(var1, var2, color='purple',
            s=80, alpha=0.7, edgecolors='black')

# 3. Elementos do gráfico
plt.title('Variávais do questionário',
          fontsize=14, fontweight='bold')
plt.xlabel('Idade (em anos)', fontsize=10)
plt.ylabel('Leituras por ano', fontsize=10)

# 4. Estética
plt.grid(True, linestyle=':', alpha=0.6)
plt.tight_layout()
plt.show()

"""# **Tabela de Frequências**"""

import pandas as pd

# Carregando os dados
df = pd.read_excel("[Estatistica-BCD]_DadosTratados_CalourosBCD_turmA.xlsx",
                   sheet_name='DadosTratados2')

# Contagem de Frequência Absoluta
frequencia_absoluta = df['Cidade_Reside'].value_counts()

# Contagem de Frequência Relativa (%)
frequencia_relativa = (df['Cidade_Reside'].value_counts(normalize=True) * 100).round(2)

print("Frequência Absoluta:\n", frequencia_absoluta)
print("\nFrequência Percentual:\n", frequencia_relativa)

# Juntando no mesmo DataFrame
tabela_frequencia = pd.concat([frequencia_absoluta, frequencia_relativa], axis=1)

# Renomeando as colunas para ficar profissional
tabela_frequencia.columns = ['Frequência Absoluta (n)', 'Frequência Relativa (%)']

print(tabela_frequencia)

# Contanto um única valor: função count()

lista = df['Cidade_Reside'].tolist()
qtd_blumenau = lista.count('Blumenau') # Conta apenas quantas vezes 'Blumenau' aparece
qtd_blumenau

"""# **Separatrizes**"""

import numpy as np

notas = [0.0, 2.5, 5.0, 6.0, 6.0, 7.0, 7.5, 8.0, 8.5, 9.5]

Q1 = np.percentile(notas,25,method="inverted_cdf")
Q2 = np.percentile(notas,50,method="inverted_cdf")
Q3 = np.percentile(notas,75,method="inverted_cdf")

print(Q1)
print(Q2)
print(Q3)

df = pd.read_excel("[Estatistica-BCD]_DadosTratados_CalourosBCD_turmA.xlsx",
                   sheet_name='DadosTratados2')

dados = df['Idade'].dropna()

Q1 = np.percentile(dados,25)
Q2 = np.percentile(dados,50)
Q3 = np.percentile(dados,75)

D1 = np.percentile(dados,10)
D5 = np.percentile(dados,50)
D9 = np.percentile(dados,90)

P5 = np.percentile(dados,5)
P95 = np.percentile(dados,95)

print(f'Quartis: Q1={Q1}, Q2={Q2}, Q3={Q3}')
print(f'Decis: D1={D1}, D5={D5}, D9={D9}')
print(f'Percentil: P5={P5}, P95={P95}')

"""# **Boxplot**"""

import matplotlib.pyplot as plt

# Dados
notas = [0.0, 2.5, 5.0, 6.0, 6.0, 7.0, 7.5, 8.0, 8.5, 9.5]

# Criando o gráfico
plt.figure(figsize=(4, 6))
plt.boxplot(notas,
            vert=True,  # Gráfico na Vertical
            patch_artist=True,
            boxprops=dict(facecolor="skyblue", color="navy"),
            medianprops=dict(color="red", linewidth=2),
            flierprops=dict(marker='o', markerfacecolor='orange', markersize=8))

# Personalização da figura
plt.title("Notas da Prova", fontsize=14, fontweight='bold')
plt.xticks([1], ["Turma A"])
plt.ylabel("Escala de notas", fontsize=12)
plt.grid(axis='y', linestyle='--', alpha=0.6)

# 4. Exibindo os limites no eixo Y
plt.yticks(np.arange(0, 11, 1))

# Salvando a imagem para o material
plt.savefig("Figura1.png", dpi=300)

# Carregando os dados
df = pd.read_excel("[Estatistica-BCD]_DadosTratados_CalourosBCD_turmA.xlsx",
                   sheet_name='DadosTratados2')
idade = df['Idade'].dropna()

# Gráfico
plt.figure(figsize=(4, 6))
plt.boxplot(idade,
            vert=True,
            patch_artist=True,
            boxprops=dict(facecolor="skyblue", color="navy"),
            medianprops=dict(color="red", linewidth=2),
            flierprops=dict(marker='o', markerfacecolor='orange', markersize=8))

# Personalização
plt.title("Idades da turma", fontsize=14, fontweight='bold')
plt.xticks([1], ["Turma A"])
plt.ylabel("Idade", fontsize=12)
plt.grid(axis='y', linestyle='--', alpha=0.6)
plt.yticks(np.arange(0, 55, 5))

# Dados
idade = df['Idade'].dropna()
leituras = df['Leituras'].dropna()
dados = [idade, leituras]  # inserir todos as variáveis em uma lista

# Gráfico
plt.figure(figsize=(4, 6))
plt.boxplot(dados,
            vert=True,
            patch_artist=True,
            boxprops=dict(facecolor="skyblue", color="navy"),
            medianprops=dict(color="red", linewidth=2),
            flierprops=dict(marker='o', markerfacecolor='orange', markersize=8))

# Personalização
plt.title("Questionário", fontsize=14, fontweight='bold')
plt.xticks([1, 2], ["Idade", "Leituras"])
plt.ylabel("Valor", fontsize=12)
plt.grid(axis='y', linestyle='--', alpha=0.6)
plt.yticks(np.arange(0, 55, 5))

"""# **Assimetria e Curtose**"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Gerar 1000 números inteiros aleatórios entre 17 e 60
np.random.seed(42)   # Garante reprodutibilidade
valores = np.random.randint(low=17, high=60, size=1000)
valores = pd.Series(valores)

# Cálculo da Assimetria
assimetria = valores.skew()

# Cálculo da Curtose
curtose = valores.kurtosis()

print(f"Assimetria: {assimetria:.2f}")
print(f"Curtose: {curtose:.2f}")

from scipy.stats import gaussian_kde

# Criando um histograma
plt.hist(valores, bins=11, density=True, color='seagreen', edgecolor='black', alpha=0.5)

# Calculando e desenhando a curva de Densidade (KDE)
kde = gaussian_kde(valores)
eixo_x = np.linspace(min(valores), max(valores), 200) # Cria pontos do início ao fim do gráfico
plt.plot(eixo_x, kde(eixo_x), color='darkgreen', linewidth=2, label='Densidade (KDE)')

# Adicionando as linhas de Média e Mediana (Exatamente igual ao seu)
plt.axvline(valores.mean(), color='red', linestyle='--', label=f'Média: {valores.mean():.2f}')
plt.axvline(valores.median(), color='blue', linestyle='-', label=f'Mediana: {valores.median():.2f}')

# Personalização
plt.title(f'Análise da Forma da Distribuição\nAssimetria: {assimetria:.2f} | Curtose: {curtose:.2f}',
          fontsize=14, fontweight='bold')
plt.xlabel('Valores', fontsize=12)
plt.ylabel('Densidade', fontsize=12)
plt.legend()

plt.tight_layout()

plt.show()

"""
Estudo da Assimetria e Curtose
"""

# Gerando dados aleatórios com o Numpy
np.random.seed(42)
n = 1000
min = 17
max = 60

normal   = np.clip(np.random.normal(43, 8, n), min, max)
ass_pos  = np.clip(np.random.gamma(shape=2, scale=10, size=n) + 17, min, max)
ass_neg  = np.clip(max - np.random.gamma(shape=2, scale=10, size=n), min, max)
curt_pos = np.clip(np.random.laplace(43, 5, n), min, max)
curt_neg = np.random.uniform(min, max, n)

# Criando a estrutura da figura
fig, axes = plt.subplots(3, 2, figsize=(12, 15))
axes = axes.flatten() # Transforma a grade em uma lista: axes[0], axes[1]...

# --- GRÁFICO 1: NORMAL ---
ax = axes[0]
ax.hist(normal, bins=12, density=True, color='lightgray', edgecolor='white')
pd.Series(normal).plot(kind='kde', ax=ax, color='seagreen')
ax.axvline(np.mean(normal), color='red', linestyle='--', label='Média')
ax.axvline(np.median(normal), color='blue', label='Mediana')
ax.set_title(f"Normal\nAssimetria: {pd.Series(normal).skew():.2f}")
ax.legend()

# --- GRÁFICO 2: ASSIMETRIA POSITIVA ---
ax = axes[1]
ax.hist(ass_pos, bins=12, density=True, color='lightgray', edgecolor='white')
pd.Series(ass_pos).plot(kind='kde', ax=ax, color='seagreen')
ax.axvline(np.mean(ass_pos), color='red', linestyle='--')
ax.axvline(np.median(ass_pos), color='blue')
ax.set_title(f"Assimetria Positiva\nAssimetria: {pd.Series(ass_pos).skew():.2f}")

# --- GRÁFICO 3: ASSIMETRIA NEGATIVA ---
ax = axes[2]
ax.hist(ass_neg, bins=12, density=True, color='lightgray', edgecolor='white')
pd.Series(ass_neg).plot(kind='kde', ax=ax, color='seagreen')
ax.axvline(np.mean(ass_neg), color='red', linestyle='--')
ax.axvline(np.median(ass_neg), color='blue')
ax.set_title(f"Assimetria Negativa\nAssimetria: {pd.Series(ass_neg).skew():.2f}")

# --- GRÁFICO 4: CURTOSE POSITIVA ---
ax = axes[3]
ax.hist(curt_pos, bins=12, density=True, color='lightgray', edgecolor='white')
pd.Series(curt_pos).plot(kind='kde', ax=ax, color='seagreen')
ax.set_title(f"Curtose Positiva\nCurtose: {pd.Series(curt_pos).kurt():.2f}")

# --- GRÁFICO 5: CURTOSE NEGATIVA ---
ax = axes[4]
ax.hist(curt_neg, bins=12, density=True, color='lightgray', edgecolor='white')
pd.Series(curt_neg).plot(kind='kde', ax=ax, color='seagreen')
ax.set_title(f"Curtose Negativa\nCurtose: {pd.Series(curt_neg).kurt():.2f}")

# --- GRÁFICO 6: CURTOSE NORMAL (MESOCÚRTICA) ---
ax = axes[5]
ax.hist(normal, bins=12, density=True, color='lightgray', edgecolor='white')
pd.Series(normal).plot(kind='kde', ax=ax, color='seagreen')
curt_normal_val = pd.Series(normal).kurt()
ax.set_title(f"Curtose Normal (Mesocúrtica)\nCurtose: {curt_normal_val:.2f}")

plt.tight_layout()
plt.show()